# Generated by Django 3.2.6 on 2021-08-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericfileupload',
            name='file_upload',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
